### ISSUE TITLE
UID/GUIDs

### ISSUE THREAD

**Issue by geodose** [jsknnr/enshrouded-server#23]
Would it be possible to expose the container permissions configuration as environment variables instead of being hard locked to 10000/10000? Having trouble integrating this into TrueNAS Scale, and I suspect it'd be tough to do with container hosts that are already setup with users/groups.

**Comment by jsknnr** [comment]
@geodose how would you feel if I made the change as a build parameter and you built the image locally with the UID and GID that you needed? I have been trying to build something that worked without a system to broker the processes like supervisor and I just don't think it is possible. I have been trying to be creative but I always land on the root process being root and at that point I might as well migrate everything to being managed by something like supervisor.

**Comment by jsknnr** [comment]
My latest release allows you to pass a build argument to the image to specify the UID and GID. So if you'd like to run the container processes as a different user, you can build the image locally and set those IDs to what you prefer.
