### ISSUE TITLE
server wont start, file missing? 

### ISSUE THREAD

**Issue by olterman** [jsknnr/enshrouded-server#30]
here is the output from docker compose .-.. 

# docker-compose up 
Starting steam_enshrouded_1 ... done
Attaching to steam_enshrouded_1
enshrouded_1  | INFO: Updating Enshrouded Dedicated Server
enshrouded_1  | tid(12) burning pthread_key_t == 0 so we never use it
enshrouded_1  | WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
enshrouded_1  | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
enshrouded_1  | Logging directory: '/home/steam/Steam/logs'
enshrouded_1  | [  0%] Checking for available updates...
enshrouded_1  | [----] Verifying installation...
enshrouded_1  | Steam Console Client (c) Valve Corporation - version 1705108307
enshrouded_1  | -- type 'quit' to exit --
enshrouded_1  | Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
enshrouded_1  | OK
enshrouded_1  | "@sSteamCmdForcePlatformType" = "windows"
enshrouded_1  | 
enshrouded_1  | Connecting anonymously to Steam Public...OK
enshrouded_1  | Waiting for client config...OK
enshrouded_1  | Waiting for user info...OK
enshrouded_1  |  Update state (0x0) unknown, progress: 0.00 (0 / 0)
enshrouded_1  | Error! App '2278520' state is 0x202 after update job.
enshrouded_1  | ERROR: steamcmd was unable to successfully initialize and update Enshrouded...
enshrouded_1  | Steam may be experiencing network issues or this container host may be experiencing network issues
steam_enshrouded_1 exited with code 1

**Comment by jsknnr** [comment]
steamcmd failed to download enshrouded server files. This is either due to a network issue with your server or steam itself, or, in this case I believe error 0x202 is insufficient storage.

**Comment by olterman** [comment]
I found this, it required to have double the storage capacity of the actual size
