### ISSUE TITLE
No persistent storage? 

### ISSUE THREAD

**Issue by olterman** [jsknnr/enshrouded-server#33]
After having gotten it to work, there are no files in my savegame forlder, the folder is mounted as it should ... are the files seaved in a different location in the docker  container ? 

# docker ps

CONTAINER ID   IMAGE                                      COMMAND                  CREATED       STATUS       PORTS                                                                                                                                  NAMES
8a0002817f1c   sknnr/enshrouded-dedicated-server:v2.0.1   "/home/steam/entrypo…"   7 hours ago   Up 7 hours   0.0.0.0:15636-15637->15636-15637/udp, :::15636-15637->15636-15637/udp                                                                  steam_enshrouded_1

# docker inspect -f '{{ .Mounts }}' 8a0002817f1c
[{volume steam_enshrouded-persistent-data /home/docker/volumes/steam_enshrouded-persistent-data/_data /home/steam/enshrouded/savegame local rw true }]

**Comment by jsknnr** [comment]
It definitely persists. The server saves every 5 minutes.

**Comment by olterman** [comment]
Well there are no files in there and I played for hours

**Comment by DutchKevv** [comment]
I'm using this container since 2 days, multiple players and even restarted the container 2 times. Data persists.

Maybe permission issue?

**Comment by olterman** [comment]
ok so, I was under false impression that it would create savegame dtat in my /home/steam /enshrouded/savegame that I had changed ownership to steam uid 10000 it does create the savegame data in the docker folder under volumes ...

**Comment by nanimosiranai** [comment]
> ok so, I was under false impression that it would create savegame dtat in my /home/steam /enshrouded/savegame that I had changed ownership to steam uid 10000 it does create the savegame data in the docker folder under volumes ...

I want to backup saved data manually.
Could you please tell me about this command?
