### ISSUE TITLE
App '2278520' state is 0x202 after update job.

### ISSUE THREAD

**Issue by maddig21** [jsknnr/enshrouded-server#38]
Hi,

i got the following error, when iam starting the container the first time:

`"@sSteamCmdForcePlatformType" = "windows"

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '2278520' state is 0x202 after update job.
ERROR: steamcmd was unable to successfully initialize and update Enshrouded...`

Yesterday i ran it on an intel nuc with the same system version (Ubuntu 22.04.3 LTS) and the latest docker version and it worked. The server was ultra laggy, so i switched to my hypervisor.

I read online, that the 202 error has to do with disk space, but how can i check this in docker?
Iam not too deep into docker :(

Thank you for your help

**Comment by sgoth** [comment]
I do get the same error with either a volume or a bind mount with correct permissions and enough space.

```
[----] Update complete, launching Steamcmd...   
tid(35) burning pthread_key_t == 0 so we never use it                                                    
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.                                                                                                                
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'                                                                                                                                                          
Logging directory: '/home/steam/Steam/logs'     
[  0%] Checking for available updates...                                                                                                                                                                           
[----] Verifying installation...                                                                                                                                                                                   
Steam Console Client (c) Valve Corporation - version 1705108307                                                                                                                                                    
-- type 'quit' to exit --                                                                                
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory                                                                                     
OK                                                
"@sSteamCmdForcePlatformType" = "windows"                                                                                                                                                                          
                                                                                                                                                                                                                   
Connecting anonymously to Steam Public...OK     
Waiting for client config...OK                  
Waiting for user info...OK                                                                               
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)                                                
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)                                                
Error! App '2278520' state is 0x202 after update job.         
                                           
ERROR: steamcmd was unable to successfully initialize and update Enshrouded...   
```

Initial install works - then it breaks.
The `Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory ` looks suspicious.

Do you get that in a working container too @jsknnr?

**Comment by jsknnr** [comment]
Yeah you can ignore the steamservice.so error. I am not sure on that error if the permissions are correct and you have available storage. I test my container on 2 completely different machines (WSL2 using Podman, and Kubernetes with containerd) and have never ran into that specific error.

**Comment by sgoth** [comment]
This is docker on debian 12.
And you're right - fixing the steamservice.so issue doesn't help either... hm.

**Comment by jsknnr** [comment]
Try running my image without compose, just copy and paste the docker command instructions as is without any edits at all. Just for troubleshooting purposes.

**Comment by sgoth** [comment]
> Try running my image without compose, just copy and paste the docker command instructions as is without any edits at all. Just for troubleshooting purposes.

My runs were (pretty much) like that already. Also have the exact same issue with `mbround18/enshrouded-docker`. Probably something unrelated to your container file. 🤷🏻

**Comment by maddig21** [comment]
Ok never mind, i increased my / partition to arround 100GB, before it was only 25GB and after extracting etc the server needs arround 30GB.With the increased space, the server runs perfect. I will close this issue. Thank you.Am 30.01.2024 um 10:04 schrieb Sebastian Goth ***@***.***>:﻿

Try running my image without compose, just copy and paste the docker command instructions as is without any edits at all. Just for troubleshooting purposes.

My runs were (pretty much) like that already. Also have the exact same issue with mbround18/enshrouded-docker. Probably something unrelated to your container file. 🤷🏻
