### ISSUE TITLE
Helm server ip

### ISSUE THREAD

**Issue by yokaimeow** [jsknnr/enshrouded-server#39]
my local k8s use metallb,default helm ignore server ip setting

my svc:

![lb](https://github.com/jsknnr/enshrouded-server/assets/46237037/dca781c5-2708-41dc-ace1-5b6ea8bd144d)

but the game server use my public ip:

![ip](https://github.com/jsknnr/enshrouded-server/assets/46237037/f4ad3c9b-9d50-4c5a-8f53-2e63501031d0)

how can i fix this,thk

**Comment by yokaimeow** [comment]
```shell
$ nc -z -u -v 192.168.50.182 15636
Ncat: Version 7.92 ( https://nmap.org/ncat )
Ncat: Connected to 192.168.50.182:15636.
Ncat: Connection refused.
```

```shell
$ nc -z -u -v 192.168.50.182 15637
Ncat: Version 7.92 ( https://nmap.org/ncat )
Ncat: Connected to 192.168.50.182:15637.
Ncat: UDP packet sent successfully
Ncat: 1 bytes sent, 0 bytes received in 2.05 seconds.
```

**Comment by jsknnr** [comment]
The server ip variable is to help the server know which interface to listen on. It is ignored in helm because really it isn't needed at all. The public IP is because it is reaching out to epic online services and getting your public IP address from there. Nothing I can do about that.

**Comment by yokaimeow** [comment]
thk
