### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by bdbais** [jsknnr/enshrouded-server#40]
Hi we are trying your docker and we has some performance problem, the server said it's overloaded but we are only in 2, is it a temporally caching situation?

**Comment by jsknnr** [comment]
No there is nothing like that on the image. The image is just Debian 11 with Wine and the server files from Steam. If you are having performance issues it could be related to network performance, or the server where you are running the container is not capable of keeping up. I cannot support issues that aren't directly related to the container image.

**Comment by broizter** [comment]
According to some random comment on Reddit proton would be better performance wise instead of wine. Could be worth switching over or releasing two different versions.

**Comment by jsknnr** [comment]
If you are having performance issues with Wine with 2 people I sincerely doubt that Podman would give you that much better performance. I have had requests for a Proton based image with people claiming amazing results, but I am skeptical. However, I have built Proton based images for servers before and could probably have 1 ready quite quick.

**Comment by broizter** [comment]
One comment claims half the CPU usage with proton so if you have a system that's right on the edge it could be the difference maker!

**Comment by brettinternet** [comment]
Probably unrelated to this image, but adding here in case someone sees something similar. I'm getting major rubber-banding once a second player joins on a server with 8+ physical cores and 32g+ of memory with the CPU never peaking above 50% load. Looks like the culprit may be packet loss:

```
[session] Pending packets list is full. Deleted oldest packet from 2(3)
```

Wondering if it could be related to differing MTU sizes? Seems unlikely.

**Comment by gary9630** [comment]
> According to some random comment on Reddit proton would be better performance wise instead of wine. Could be worth switching over or releasing two different versions.

I believe it is this post on Reddit: https://www.reddit.com/r/Enshrouded/comments/1abb0q4/dedicated_server_help_lag_rubberbanding/

**Comment by jsknnr** [comment]
You guys are forcing my hand. I'll have a proton image shortly.

**Comment by broizter** [comment]
I have done some testing and I can confirm a significant CPU load reduction switching to Proton. Not half but still!
![wine](https://github.com/jsknnr/enshrouded-server/assets/39500356/9257105f-6232-4477-9696-c112b4e26232)
![proto](https://github.com/jsknnr/enshrouded-server/assets/39500356/263d468b-5da1-4105-bc2c-d163596bc3b0)

**Comment by broizter** [comment]
@gary9630 That's the docker images I used to make the comparison! But yes I agree if people are seeing performance issues but the CPU load is not close to 100% then this change will not help and is caused by something else. I've had no performance issues at all using both images with 2 people playing.

**Comment by gary9630** [comment]
@broizter Yeah! The wine-based image is worked just fined when my server with people less or equal than 4. However, once the player number > 4, things went crazy. Initially, I used a 4 cores machine, the CPU load is around 75% when players > 4. So I switch to a machine with 8 cores thinking that the greater CPU will solve the lag issue. But the over-4 lag is still the same. :(

**Comment by cropse** [comment]
I think even I quit the game with no player login, it took almost same cpu usage, even no one logined at night. perform issue is quite a thing. I install this image in Jan 28 and this is my CPU report in 6 core machine.
![image](https://github.com/jsknnr/enshrouded-server/assets/8165650/79f2ec52-f80c-4644-a48b-0566ccbd5470)

**Comment by ckooistra** [comment]
Hey just want to add my two cents.  First this image has been great and I am up and running thank you for whipping this up so quickly!  Like others have mentioned the resource use has been really high for this  like much higher than all my other docker images even when no one is connected.
![image](https://github.com/jsknnr/enshrouded-server/assets/25510870/7a7e9808-daad-485a-b220-7f0b041aea82)

You can see when everyone left the server last night the cpu usage dropped from almost 600% to 400%  excited to see what the proton image will be able to do.  I would assume that we will be able to use the persistent data volume to persist the world with the new image?  Thanks again!

**Comment by jsknnr** [comment]
I have a proton image built. I need to do a bit more testing with it and then I am going to quietly release it for folks to test.

**Comment by Robert-Langbein** [comment]
> If any one is willing to give it a test, I have pushed the image to Docker Hub `sknnr/enshrouded-dedicated-server:proton-latest`

Amazing! Have had the same issues with server overload >1 player and we couldn't event use meele attacks as they did not hit. Works now great with the proton image. Got an 8 vcore cloud server with 24gb ram and synchronous 400mbit, so the issue couldn't be the server itself as everything else is running smooth on that machine. 

Anyways, thanks for the nice work here!

**Comment by jsknnr** [comment]
@Robert-Langbein I am glad it's working better for you now. One thing to keep in mind is that Enshrouded devs built their own game engine for this so I am sure there is a lot of performance optimizations and bug fixes yet to made on the multiplayer backend. On top of us tricking the server to thinking it's running in a Windows environment :)

**Comment by ckooistra** [comment]
Hey I would like to try it out.  Can I just swap that image and attach it to the volume I already created?

**Comment by jsknnr** [comment]
@ckooistra You can.

**Comment by ckooistra** [comment]
Hi so far looking good the CPU usage has dropped significantly!
![image](https://github.com/jsknnr/enshrouded-server/assets/25510870/272eb08d-1bb0-46bb-a444-fab23f9e3017)
Thanks again @jsknnr!

**Comment by ckooistra** [comment]
Actually I cannot connect to the instance?  I keep getting this error but I don't see any log output on the docker container.  Do you  know where else I could look?
![image](https://github.com/jsknnr/enshrouded-server/assets/25510870/ea2b956d-58e1-4707-9fd7-b7c508933a48)

**Comment by ckooistra** [comment]
Great thanks lol that fixed it!  I had thought redeploying the stack would have done it.

**Comment by eric-beaudoin** [comment]
I confirm the Proton-based container is significantly better.
5-player game on Wine was so laggy it was unplayable. With Proton it is smooth.
Thanks @jsknnr

**Comment by marcus-jan** [comment]
Confirming as well that the proton container performs much better. My server has 3 players and all have seen the improvement instantly. Good work @jsknnr !

**Comment by TrueOsiris** [comment]
> I also ran into this issue. When the server join more than 4 players, suddenly the ping for all players in the game increases insanely high (20ms to over 10000ms). However, I monitor the CPU and MEM usage, there are still quite many resources.
> 
> ![1706544949498](https://private-user-images.githubusercontent.com/31646293/300560634-fd27a0f0-bc57-4dec-ab53-328050be383d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MTk0OTgsIm5iZiI6MTcwNjkxOTE5OCwicGF0aCI6Ii8zMTY0NjI5My8zMDA1NjA2MzQtZmQyN2EwZjAtYmM1Ny00ZGVjLWFiNTMtMzI4MDUwYmUzODNkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDAwMTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ZWM2MjY1Y2I5OTU3YTAzY2Y3NjQzMTUyM2RjNzFkODNhYjZiYzYwODY5Y2MyZjA4M2FiN2VmYWFiYjdkOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yNpFaLy6vi6ZVXserJvhPc7ofFXd3eg1G_yHuklzQsI)
> 
> Pretty weird.

We encounter similar issues, with a 4th player lagging often.
Spinned up my Xeon with only 1 docker container running this. 
Is the problem wine? are u using wine32?

I'm testing the proton version.

**Comment by cgarnier** [comment]
Did you manage to switch without loosing the save ?

**Comment by McAwsm94** [comment]
I switched from wine to proton and I didn't lost anything... (with docker / DSM 7). Deleted wine image, installed proton image **with same name for container**. Nothing to do if you already had a savegame with jsknnr/enshrouded wine image.

**Comment by cgarnier** [comment]
Great @McAwsm94 , good job @jsknnr

**Comment by Juwi2** [comment]
> > If any one is willing to give it a test, I have pushed the image to Docker Hub `sknnr/enshrouded-dedicated-server:proton-latest`
> 
> Hey @jsknnr,
> 
> I just installed it via Docker on my Synology server. For now, it's working great! There are 4 of us connected, no more lag! Thanks!

Hi @jbgaf,
how do you manage the Enshrouded world savegame within the Synology Container Station, because I want to copy a local Enshrouded savegame to my dedicated Server folder? What are your "Environments variables" in Synology Container Station? Can you share a Screenshot?

I was able to start @jsknnr latest proton release and can connect via steam to my Server but when I change the persistant storage (ENSHROUDED_PATH) to my synology path outside the docker, I am unable to start the sknnr Enshrouded dedicated server, although I made "chown -R 10000:10000 /volume1/docker/enshrouded" including subfolders.

**Attachments**
1. My Container Station environments variables:
![sknnr-enshrouded-dedicated-server config](https://github.com/jsknnr/enshrouded-server/assets/118803807/0d3d2b36-6067-47ad-ad0d-77dcb0a82f83)

2. My protocoll from jsknnr Enshrouded Dedicated Container:
![sknnr-enshrouded-dedicated-server logfiles-protocoll](https://github.com/jsknnr/enshrouded-server/assets/118803807/f8a766d8-eace-4515-8c72-22db0b389cd7)

**Comment by jbgaf** [comment]
> > > If any one is willing to give it a test, I have pushed the image to Docker Hub `sknnr/enshrouded-dedicated-server:proton-latest`
> > 
> > 
> > Hey @jsknnr,
> > I just installed it via Docker on my Synology server. For now, it's working great! There are 4 of us connected, no more lag! Thanks!
> 
> Hi @jbgaf, how do you manage the Enshrouded world savegame within the Synology Container Station, because I want to copy a local Enshrouded savegame to my dedicated Server folder? What are your "Environments variables" in Synology Container Station? Can you share a Screenshot? Refer to my config under attachments (1).
> 
> I was able to start @jsknnr latest proton release and can connect via steam to my Server but when I change the persistant storage (ENSHROUDED_PATH) to my synology path outside the docker, I am unable to start the sknnr Enshrouded dedicated server, although I made "chown -R 10000:10000 /volume1/docker/enshrouded" including subfolders. Refer to my error message under attachments (2.)
> 
> **Attachments**
> 
> 1. My Container Station environments variables:
>    ![sknnr-enshrouded-dedicated-server config](https://private-user-images.githubusercontent.com/118803807/309725247-0d3d2b36-6067-47ad-ad0d-77dcb0a82f83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NDUyNTEsIm5iZiI6MTcxMDQ0NDk1MSwicGF0aCI6Ii8xMTg4MDM4MDcvMzA5NzI1MjQ3LTBkM2QyYjM2LTYwNjctNDdhZC1hZDBkLTc3ZGNiMGE4MmY4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQxOTM1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGNlYTNkMWFlYjJlMmZkYWZhNDRmMDU2NjFhODMxYzZjNmYzNDMxMzQyZWE1ODNkNTc5NzEzN2I4M2FiN2JmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GUT3fdB9YhJdSEpCO3OAv2sWCnk-PPD1P2qQUKeVye8)
> 2. My protocoll from jsknnr Enshrouded Dedicated Container:
>    ![sknnr-enshrouded-dedicated-server logfiles-protocoll](https://private-user-images.githubusercontent.com/118803807/309725847-f8a766d8-eace-4515-8c72-22db0b389cd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NDUyNTEsIm5iZiI6MTcxMDQ0NDk1MSwicGF0aCI6Ii8xMTg4MDM4MDcvMzA5NzI1ODQ3LWY4YTc2NmQ4LWVhY2UtNDUxNS04YzcyLTIyZGIwYjM4OWNkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQxOTM1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjAzN2I3ZTg0MzlhODcwMDQ2ODJjYWM3OTZjZDcwODYwOTQxMTJjZDM0MDU1MGIyYjQ4ZjdjOTZlNmYwNmZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SamTPw7oSyUaEIY6hMZfAfZuRawTHic-JVp0curXYDc)
> 
> Thank you in advance! Yours sincerly Juwi.

Hey,

Why do you change your ENSHROUDED PATH ? 

I first launch Enshrouded server with proton image. I launch game and go into server. Game will create save files into the container.

Then, I shut the container off and I copy my local savegame files into container with commands lines. For that, you need to use command "docker cp" (and you need to install docker). 

As you can see, I didn't need to change Environments variables. 

![image](https://github.com/jsknnr/enshrouded-server/assets/43916107/4d0035d5-ae11-4818-98ad-ffc77fbb9549)
