### ISSUE TITLE
Possibility to Change UID and GID

### ISSUE THREAD

**Issue by fetpols** [jsknnr/enshrouded-server#51]
I'm testing on a Synology NAS, and everything works perfectly except for the game save feature. Synology doesn't allow changing the UID and GID of modified users through the console. I've seen other ways to force it, but I'd prefer not to tinker too much with the system. Is there any way to choose different UID and GID? Thank you very much

**Comment by jsknnr** [comment]
My image runs as non root with UID:GID of 10000 for security and to avoid host ID collisions. This is best practice. However, if you absolutely need to change the UID:GID for the container, you can build the image your self. My image will never run as root as that is not how I build images, so there is no way for me through start env vars to change UID:GID. I have however added the ability for it to be specified on image build.

Grab all the files for the image you want to build (wine/proton) from my repo (or just clone the repo) from `/container/` directory. Once you have all the files, go to that directory locally and:

`docker build --build-arg="CONTAINER_UID=N" --build-arg="CONTAINER_GID=N" -t my-enshrouded:latest .`

Once the build is finished, you can then run with your custom built image. If you're running compose or docker directly or whatever, just change the image and tag to match your new built container which in the above example would be `my-enshrouded:latest`

Cheers,

**Comment by fetpols** [comment]
Wow, that was a really good explanation, I appreciate it. It worked perfectly for me

**Comment by jsknnr** [comment]
Glad to hear it. Have fun.

**Comment by eviltek2099** [comment]
I'm attempting to run on Docker Desktop and the UID:GID requirement is causing the docker to not start. I see "Rm cannot remove Device or resource busy" on enshrouded_server.json if I have " - ./enshrouded_server.json:/home/steam/enshrouded/enshrouded_server.json" in my docker-compose.yml
