### ISSUE TITLE
Loss of backup after update

### ISSUE THREAD

**Issue by Ishtakh** [jsknnr/enshrouded-server#53]
Hello

I would like to report an issue I encountered after updating to the latest Wine version.
This morning my container had crashed, so before I restarted it I checked for a new version, there was one ( before that I used the pre-launch one)

Update went well, but when I logged backed in, I discovered my world was reset.

I use Portainer CE to manage my container, here's the command I passed when creating it the first time : 

 `docker run --detach --name enshrouded-server --mount type=volume,source=Enshrouded_data,target=/var/lib/docker/volumes/Enshrouded_data/_data --publish 15636:15636/udp --publish 15637:15637/udp --env=SERVER_NAME="My Server Name" --env=SERVER_SLOTS=4 --env=SERVER_PASSWORD="My Server Password" --env=GAME_PORT=15636 --env=QUERY_PORT=15637 sknnr/enshrouded-dedicated-server:latest`

It's basically what was in your guide, but I saw it has changed since.

Best regards, and many thanks for your work

**Comment by jsknnr** [comment]
Do you by chance remember which tag you were using prior? If it was old enough, I changed the UID:GID to reduce the risk of container host ID collisions. You may have to reset the permissions on the volume to the host. Try this: `chown -R 10000:1000 /var/lib/docker/volumes/Enshrouded_data` . Also, in your docker run command, your mount option is wrong. You need to do `--mount type=volume,source=Enshrouded_data,target=/home/steam/enshrouded/savegame`

**Comment by Ishtakh** [comment]
Thanks for the chown and the mount option, it works again.

I know where I fucked up, I copied the mount point Portainer gave me in place of what was written in your command because I still struggle a little with Docker. Well, you learn everyday !

Thanks again for you help and your work.

PS: switched to proton, server uses half CPU compared to Wine
