### ISSUE TITLE
proton-latest: extreme rubber banding since recent update

### ISSUE THREAD

**Issue by MiguelP0** [jsknnr/enshrouded-server#55]
Thanks, for putting this together. We are experiencing extreme rubberbanding since the newest Update.

**Comment by jsknnr** [comment]
Which image are you using?

**Comment by Goigelel** [comment]
sknnr/enshrouded-dedicated-server:proton-latest

**Comment by jsknnr** [comment]
Odd - most folks report much better performance with the proton version. You can try the latest wine version to see if that's any better for you.

**Comment by Goigelel** [comment]
I had much better Performance with Proton compared to Wine before the Update, i'll try that though. Thanks
