### ISSUE TITLE
failed to register layer: lsetxattr user.overlay.impure /etc: operation not supported

### ISSUE THREAD

**Issue by dreesi** [jsknnr/enshrouded-server#56]
Hey there,

i am relatively new to the docker party and tried to use your description to set up a docker container with docker compose or docker, tried both. I get the same error in docker or docker compose:

`[+] Running 2/3
 ⠴ enshrouded-dedicated-server 2 layers [⣿⣿]
   ✔ 2f44b7a888fa Pull complete
   ✔ 980609f7b193 Download complete
failed to register layer: lsetxattr user.overlay.impure /etc: operation not supported`

I am aware that it's maybe an issue of my system enviroment, I use proxmox with a docker lxc.

If it's totally unrelated to your work, please close this. If you have a hint for me, It would be really appreciated :)

Great work by the way!!!

**Comment by bnwhorton** [comment]
Do other containers work for you? It looks to me like your docker daemon is unable to write layers correctly.

**Comment by KissKool-63** [comment]
I have the same problem, is there a simple solution as I'm just starting out with docker, portainer etc.?

**Comment by AliIbnIbrahim** [comment]
A have also the same problem !

**Comment by dreesi** [comment]
dumb question but can I use a dockerd < version 25.0 to avoid this problem as a workaround?

**Comment by jsknnr** [comment]
I moved the build action from buildah to buildx as part of my latest release. Let me know if this works better.
