### ISSUE TITLE
Update on TrueNas Scale ??

### ISSUE THREAD

**Issue by Clouditto** [jsknnr/enshrouded-server#62]
Hi, noob here. First time setting up a server with containers instead of VMs
Im hosting the proton-latest containter on a TrueNas Scale host using the custom App luncher I managed to setup everything no problem, but now the UI **_shows me there is an upgrade from: proton-latest_2308.0.1  to proton-latest_2403.0.0_** 

But I can´t find anything on this repository that indicates that JSKNNR has updated anything. Any changelogs at all either

Does anyone knows why there is an upgrade? 

Thanks in advance

**Comment by jsknnr** [comment]
Yeah, I am not sure where that is coming from. For proton it should be docker.io/sknnr/enshrouded-dedicated-server:proton-latest
