### ISSUE TITLE
Start area ingame - no bushes respawning without server restart

### ISSUE THREAD

**Issue by tardar** [jsknnr/enshrouded-server#63]
Hey,

can you tell me if or when the server needs an update because of changed game versions ?
mayb i do smth wrong but in our game on our server we dont see the bushes respawning within 5 hours.

Can you help / answer me ?

Thanks alot and have a nice evening
Tardar

**Comment by jsknnr** [comment]
I cannot. I could potentially implement an auto-update function in the image but I feel like it's more dependencies and work than it's really worth. Just restart the pod/container and it will update.
