### ISSUE TITLE
Graceful shutdown

### ISSUE THREAD

**Issue by Chris-D-Turk** [jsknnr/enshrouded-server#65]
First off thank you for making these images and sharing with us. The proton-based image works really good. 
But I noticed that the dedicated server is not gracefully shutting down when doing a `docker stop`. The server just gets terminated after the 10 sec timeout which could lead to a corrupted save game.
I fixed this in my fork by trapping the interrupt signal: https://github.com/Chris-D-Turk/enshrouded-docker-image/blob/develop/container/proton/entrypoint.sh
Maybe you want to apply the relevant changes to your entrypoint script.

**Comment by lkkuma** [comment]
Submit a PR to make it easier for them to do so

**Comment by jsknnr** [comment]
This is on my list of things to implement. Next version.
