### ISSUE TITLE
Password requirement for groups

### ISSUE THREAD

**Issue by decade27** [jsknnr/enshrouded-server#71]
More of a suggestion.

SERVER_PASSWORD requirement replaces any edit on the config file obviously, so making this not required would be good maybe for us to use the user group password function of the game.

Creating 2 user groups with different passwords replaces both passwords from the env SERVER_PASSWORD.

Workaround: Built the image myself by removing the required env

**Comment by jsknnr** [comment]
Yeah, I haven't looked at the new server config since the update. I will take a look at this when I get some time and do some refactoring.

**Comment by jsknnr** [comment]
New image no longer requires a password. I'll look into adding functionality for groups.

**Comment by decade27** [comment]
Awesome, thanks for that
