### ISSUE TITLE
Remove permission chown -R 10000:10000

### ISSUE THREAD

**Issue by QuentinJ54** [jsknnr/enshrouded-server#75]
Good morning,

Can you remove the requirement to use the steam user?
in fact I am on Linux and I want to use another user, so it is impossible to launch the server

**Comment by jsknnr** [comment]
The idea is that the user and group ID from within the container does NOT collide with a user on the local system. This is for security reasons. I am not willing to change this as that is not how I build containers. However, you are free to build your own image from my docker file and set the IDs to what you would like.

I have addressed this in a previous issue. Check here for instructions on how to build the image with your own user and group ID arguments.

https://github.com/jsknnr/enshrouded-server/issues/51

**Comment by andrewgdunn** [comment]
What about if you're running podman as a non-root user already?

**Comment by jsknnr** [comment]
Such a thing is possible: https://www.redhat.com/en/blog/rootless-podman-user-namespace-modes

But may I ask why? The idea is the container is self contained and it's ID's do not collide with system ID's for security reasons. The threat may be low, but it is still best practice. Ideally, you should not need to access the container files outside of the container anyway... and if you do, running `sudo` before your operation should allow you to edit a file regardless of if the UID/GID exists on your local system.

If you really hate the UID/GID that I have selected, the parameters exist as build arguments to the image so you can build your own version of my image and specify your own UID and GID and build time.
