### ISSUE TITLE
CPU spikes cause 'server overload'

### ISSUE THREAD

**Issue by Albastraoz** [jsknnr/enshrouded-server#77]
![image](https://github.com/user-attachments/assets/928143d6-9f3d-42fd-a368-8091daade330)

Whenever a user joins the server there is this CPU peak every ~30 seconds. The image is from the docker container where you can see when nobody is on the server and when somebody is. My system requirements should be good enough to run this flawless. What could be the issue in this case since I see nobody else having issues after the proton update.

**Comment by Albastraoz** [comment]
I have an Intel Nuc with this processor i3-1220P running on an Ubuntu server. There are only a few containers running and besides the enshrouded one there is nothing that takes a lot of CPU power.

**Comment by jsknnr** [comment]
It's tough to test against all the different hardware configurations and software configurations. I test from workstation using Docker and Podman from inside WSL with a Ryzen 7 5800x3d and 64GB of RAM. I also test in my lab from an HP DL360 1U server with dual Xeon Haswells and somewhere north of 100GB of RAM on Debian 12... But that is the extent of my testing.

I just released a new version of the proton image today with the latest version of Proton-GE... you can try that and see if performance is better.

**Comment by Albastraoz** [comment]
I have also tried the mornedhels setup but the same thing happens. I will try your new release this weekend and see if it helps :). Thanks for the comment. I will update you and otherwise close the ticket if there is not much to do about it.

**Comment by jsknnr** [comment]
I am also experiencing overload issues with just a few players. This was not the case previously. The devs have built their own game engine for Enshrouded and I am assuming they have either introduced some bugs in a recent update to their netcode or it simply needs more optimizations. Not much I can do about this outside of throwing faster hardware at it and hoping for the best.

**Comment by jasmor** [comment]
Just chiming in with the same issue. Running on an Azure Virtual Machine Standard_D4a_v4 4vCPU and 16GB of Memory. I also had the same issue with another docker image from another author so I'm assuming it might be on the Enshrouded side of the house.

**Comment by Albastraoz** [comment]
Yes it seems more likely a problem on the game developers side, So I will close this issue. :)
