### ISSUE TITLE
[Helm] externalConfig

### ISSUE THREAD

**Issue by Xeroxxx** [jsknnr/enshrouded-server#84]
https://github.com/jsknnr/enshrouded-server/blob/ed047064c9a9cb19a2c5ef8e92338b4b2e4627a8/helm/templates/deployment.yaml#L49

This does not work. External_Config is never set, as externalCOnfig not externalConfig.

Cant get the password to work either, maybe moving gamedata and config to persitant volume as well, so in K8S it does not download the data again and again.

Thanks for your work!

**Comment by jsknnr** [comment]
Good catch. Fixed. I may update the chart to persist game data in the future. Until then, feel free to add a PVC for the path.

**Comment by jsknnr** [comment]
I also fixed the password issue. There was a typo in the helm chart.
